### PR TITLE
Support for the jsToolbar buttons extension and WikiNG extension

### PR DESCRIPTION
**Pull request by TheMagician1**
Hi,

We have added support for the Redmine jsToolbar Buttons extension and WikiNG extension to the theme.
Also we made sure the height of more input items are aligned (text, selectbox, date, file)
Also we have altered the Wiki headers a bit: gave them no padding on top and bottom and added header 4, 5 and 6.

Regards,
Bas

### CODE REVIEW

**Comment by akabekobeko** [comment]
memo:

* should be supported by the theme specific extension corresponding?
* It may support if it is thoroughly tested
* Image want to vector image ( Icon Font )

**Comment by TheMagician1** [comment]
I would like to create the vector image. What is the best way to add the images to the Icon Font?
If the extensions are used, their buttons look like the standard theme and don't fit in when using this theme.
Thank you for considering the merge.

**Comment by akabekobeko** [comment]
memo:

* "jsToolbar Buttons Extension":http://www.redmine.org/plugins/redmine_jstoolbar_ext_buttons
* "WikiNG":http://www.redmine.org/plugins/wiking

Try these plug-ins to checkout the pull request to the local.

**Comment by akabekobeko** [comment]
@TheMagician1 

It was adopted merge.
Work for the image to vector will I support.

**Pull request merged**
